version: "3.9"
services:
  app:
    image: app:latest
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 8080:80
networks:
  app-network:
    name: app-network
